#### 1. Import the numpy package under the name `np` (★☆☆)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
np.__version__

'1.23.5'

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.empty(10)

array([5.05528123e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 6.64108274e-066, 1.16188963e+165, 5.28206026e-091,
       1.10618148e-046, 4.34243033e-315])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:

np.empty(10).size * np.empty(10).itemsize
np.empty(10).nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.add?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
null=np.full(10,fill_value=None)
null[4]=5
null

array([None, None, None, None, 5, None, None, None, None, None],
      dtype=object)

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
arr=np.arange(10,49)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
arr=arr[::-1]
arr

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
arr=np.random.randint(0,9,9).reshape(3,3)
arr

array([[2, 7, 5],
       [7, 8, 8],
       [8, 6, 1]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
np.nonzero(np.array([1,2,0,0,4,0]))

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
arr=np.random.randint(0,10,27).reshape(3,3,3)
arr

array([[[1, 4, 6],
        [7, 5, 9],
        [0, 6, 4]],

       [[4, 4, 7],
        [9, 5, 7],
        [6, 9, 6]],

       [[7, 8, 0],
        [3, 4, 1],
        [3, 3, 7]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
arr=np.random.randint(0,10,100).reshape(10,10)
print(arr)
print(np.min(arr))
print(np.max(arr))

[[8 2 3 6 5 4 4 9 2 4]
 [1 6 0 1 3 6 5 7 0 1]
 [6 9 7 0 8 5 0 4 4 0]
 [7 1 3 1 7 4 4 7 7 2]
 [4 0 1 1 8 1 3 1 4 4]
 [2 5 1 3 1 6 0 7 4 3]
 [5 0 3 7 2 6 0 1 5 8]
 [1 7 1 0 9 0 7 3 1 6]
 [3 7 7 9 2 3 3 5 8 0]
 [7 8 8 2 0 3 6 4 2 9]]
0
9


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
arr=np.random.randint(0,10,30)
print(arr)
print(np.mean(arr))

[1 1 5 3 2 4 3 6 9 8 6 1 7 7 6 4 0 9 6 9 3 5 8 8 1 3 7 1 5 7]
4.833333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a = np.ones((5,5))
a = np.pad(a,2)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
False

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
arr=np.zeros(25).reshape(5,5)
j=0
k=1
for i in range(1,5):
  arr[i,j]=k
  k+=1
  j+=1
arr

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
# black is 0
# white is 1
arr=np.zeros((8,8))
arr[::2,::2]=1
arr[1::2,1::2]=1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
arr=np.zeros((6,7,8))
index=np.unravel_index(99,arr.shape)
index

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
b=np.array([[0,1],[1,0]])
a=np.tile(b,(4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
arr=np.random.normal(0,1,25)
arr.reshape(5,5)

array([[ 0.22871698, -0.72930394,  0.3208888 ,  0.54150988, -0.79230249],
       [-0.54696943,  0.86383039,  1.63778666,  0.6148611 , -0.00365076],
       [-1.18602051,  0.7835345 , -1.30843757,  0.07038351,  0.71665256],
       [-0.68464894, -0.4496938 , -0.22613234, -1.23156256,  0.93990233],
       [ 0.78570482,  1.27594411,  1.49976061, -0.85016958, -1.03941714]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
import numpy as np
m1=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
    [13,14,15]
])
m2=np.array([
    [1,2],
    [3,4],
    [5,6]
])
a=np.dot(m1,m2)
a

array([[ 22,  28],
       [ 49,  64],
       [ 76, 100],
       [103, 136],
       [130, 172]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr[(arr>3)&(arr<8)]*=-1
print(arr)

[ 1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
#Z<Z>Z

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
# nan
# 0
# array([none])

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
import numpy as np
m1=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
    [13,14,15]
])
m2=np.array([
    [1,2],
    [3,4],
    [5,6]
])
np.intersect1d(m1,m2)

array([1, 2, 3, 4, 5, 6])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
np.warnings.filterwarnings('ignore')

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [46]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [2]:
import numpy as np
start= np.datetime64('2023-09-28')
end= np.datetime64('2023-09-30')

dates = np.arange(start, end+ np.timedelta64(1, 'D'))

print(dates)

['2023-09-28' '2023-09-29' '2023-09-30']


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [3]:
start= np.datetime64('2016-07-01')
end= np.datetime64('2023-09-30')

dates = np.arange(start, end+ np.timedelta64(1, 'D'))

print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' ... '2023-09-28' '2023-09-29'
 '2023-09-30']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [ ]:
# first solve the first pracits (A+B)
# then compute (-A/2)
# then multiply the first and the secound pracits

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [7]:
random_array = np.random.rand(5)
arr=np.floor(random_array)
print(arr)

[0. 0. 0. 0. 0.]


In [8]:
arr=np.trunc(random_array)

print(arr)

[0. 0. 0. 0. 0.]


In [9]:
arr=np.subtract(np.ceil(random_array), 1)

print(arr)

[0. 0. 0. 0. 0.]


In [11]:
arr=random_array.astype(int)

print(arr)

[0 0 0 0 0]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [4]:
m=np.random.randint(0,4,25).reshape(5,5)
m

array([[3, 3, 1, 1, 0],
       [1, 2, 2, 2, 2],
       [2, 0, 1, 2, 2],
       [1, 0, 0, 1, 0],
       [3, 3, 0, 2, 3]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [44]:
arr=np.random.randint(0,10,10)
arr

array([0, 2, 0, 7, 0, 7, 8, 1, 5, 6])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [5]:
m=np.random.randint(0,2,10)
m

array([0, 1, 1, 1, 1, 1, 1, 1, 0, 0])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [11]:
m=np.random.randint(0,10,10)
m=np.sort(m)
print(m)

[0 3 4 5 6 6 7 7 7 9]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
# if you need to sum a small array faster than np.sum(), you can consider using the built-in sum()
# function in Python instead. The sum() function is generally faster for small arrays
# because it has less overhead compared to np.sum(), which is more optimized for larger arrays and supports various advanced features.

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [12]:
A = np.random.randint(0,10,9).reshape(3,3)
B = np.random.randint(0,10,9).reshape(3,3)
np.array_equal(A, B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [2]:
import numpy as np
arr= np.array([1,2,3,4,5])
arr.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [6]:
cartesian_coords = np.random.rand(10, 2)
x = cartesian_coords[:, 0]
y = cartesian_coords[:, 1]
rho = np.hypot(x, y)
theta = np.arctan2(y, x)
polar_coords=np.column_stack((rho, theta))
print(polar_coords)

[[0.94469919 1.08255097]
 [0.58937892 1.13630646]
 [1.12048942 0.99168905]
 [0.98305012 1.13033521]
 [0.79155627 0.81807472]
 [0.92602779 1.21913827]
 [0.85251355 0.7234502 ]
 [1.1126426  0.98469975]
 [0.9464376  0.92582697]
 [0.87873855 0.35388406]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [9]:
arr=np.random.randint(0,10,10)
max=np.max(arr)
print(arr)
arr[arr==max] = 0
print(arr)

[7 6 7 3 5 7 0 8 0 1]
[7 6 7 3 5 7 0 0 0 1]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [11]:
x = np.linspace(0, 1, num=5)
y = np.linspace(0, 1, num=3)
grid = np.meshgrid(x, y)
arr = np.stack(grid, axis=-1).reshape(-1, 2)
print(arr)

[[0.   0.  ]
 [0.25 0.  ]
 [0.5  0.  ]
 [0.75 0.  ]
 [1.   0.  ]
 [0.   0.5 ]
 [0.25 0.5 ]
 [0.5  0.5 ]
 [0.75 0.5 ]
 [1.   0.5 ]
 [0.   1.  ]
 [0.25 1.  ]
 [0.5  1.  ]
 [0.75 1.  ]
 [1.   1.  ]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [12]:
x = np.array([1, 2, 3])
y = np.array([4, 5])
c = 1 / (x[:, np.newaxis] - y)
print(c)

[[-0.33333333 -0.25      ]
 [-0.5        -0.33333333]
 [-1.         -0.5       ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

In [23]:
arr=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,12]
    ])
for i in range(arr.shape[0]):
  for j in range(arr.shape[1]):
    print(arr[i,j])

1
2
3
4
5
6
7
8
9
10
11
12
13
14
12


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [27]:
arr = np.random.randint(0,10,10)
scalar = 0.5
res = arr[np.argmin(np.abs(arr - scalar))]
print(res)

3


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [25]:
dtype = np.dtype([('position', [('x', float), ('y', float)]),
                  ('color', [('r', int), ('g', int), ('b', int)])])
structured_array = np.zeros((5,), dtype=dtype)
structured_array['position']['x'] = [1.0, 2.0, 3.0, 4.0, 5.0]
structured_array['position']['y'] = [6.0, 7.0, 8.0, 9.0, 10.0]
structured_array['color']['r'] = [255, 0, 0, 0, 255]
structured_array['color']['g'] = [0, 255, 0, 0, 255]
structured_array['color']['b'] = [0, 0, 255, 0, 255]
print(structured_array)

[((1.,  6.), (255,   0,   0)) ((2.,  7.), (  0, 255,   0))
 ((3.,  8.), (  0,   0, 255)) ((4.,  9.), (  0,   0,   0))
 ((5., 10.), (255, 255, 255))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [28]:
arr= np.array([1.2, 2.5, 3.8, 4.1], dtype=np.float32)
arr.astype(np.int32, copy=False)

print(arr)

[1.2 2.5 3.8 4.1]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [43]:
arr=np.zeros(15).reshape(3,5)
for i in range(arr.shape[0]):
  for j in range(arr.shape[1]):
    try:
      arr[i][j]=int(input())
    except:
      arr[i][j]=None
arr

1
2
3
4
5
6


7
8


9
10
11


array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [19]:
arr = np.array([
    [1,2,3],
    [2,3,4],
    [4,5,6]
])
p=5
res=np.random.choice(range(arr.size),p,replace=False)
arr.flat[res] = 1
arr

array([[1, 2, 3],
       [1, 1, 1],
       [1, 5, 1]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [9]:
arr = np.array([
    [1,2,3],
    [2,3,4],
    [4,5,6]
])
m= arr-np.mean(arr,axis=1,keepdims=True)
m

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [27]:
arr = np.array([
    [1,2,3,None],
    [None,None,None,None],
    [4,5,6,None]
])
flag=0
for i in range(arr.shape[0]):
  for j in range(arr.shape[1]):
    if arr[i][j]==None:
      flag+=1
    if flag==arr.shape[1]:
      print(f"the array has the coloumn index {i} is null")
  flag=0


the array has the coloumn index 1 is null


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [33]:
arr= np.array([[1, 2, 3]])
arr2= np.array([[4],
                [5],
                [6]])

res= 0
for i in range(3):
  res+=arr[0][i]+arr2[i][0]
print(res)

21


#### 63. Create an array class that has a name attribute (★★☆)

In [29]:
class Array:
    def __init__(self, array, name):
        self.array = array
        self.name = name
arr = Array([1, 2, 3], "ahmed")
print(arr.array)
print(arr.name)

[1, 2, 3]
ahmed


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [2]:
import numpy as np
arr = np.array([
    [1,2,3],
    [2,3,4],
    [4,5,6]
])
arr=arr+1
arr

array([[2, 3, 4],
       [3, 4, 5],
       [5, 6, 7]])

In [3]:
arr=np.array([1,2,3,4,5])
a=np.array([0,2,2,4])
np.add.at(arr,a, 1)

print(arr)

[2 2 5 4 6]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [5]:
image = np.array([
    [[255,0,0],[0,255,0],[0,0,255]],
    [[255,0,0],[0,255,0],[0,0,255]],
    [[255,255,0],[0,255,255],[255,0,255]]
], dtype=np.ubyte)
reshaped_image=image.reshape((-1,3))
num_unique_colors=len(np.unique(reshaped_image,axis=0))
print(num_unique_colors)

6


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)